name: pwacam
description: "A new Flutter project."

version: 1.0.3+3

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  path_provider: ^2.1.5
  video_player: ^2.10.0
  shared_preferences: ^2.5.3
  http: ^1.1.0
  passkeys: ^2.15.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  sw: ^0.0.5

flutter:
  uses-material-design: true
